"""Aggregate chirp-loop NVS sweep results into ``md/chirp_loop_nvs_sweep.md``.

Reads ``mm25DGS_v5_v4/output_chirp_loop/<scene>_<tag>/results.json`` from the
per-experiment output directories and produces a single markdown report
with per-scene and overall summaries:

    * upper-bound cc (trained on all 16 chirp loops, per-frame)
    * held-out test cc  (held-out loop 8, per-frame)
    * gap  = upper_bound − held_out  (interpolation residual)
    * init cc (untrained) per-frame, per-mode
    * per-scene means + grand means

The report is written whether or not the sweep is complete — frames
that haven't produced a results.json yet are marked as ``–`` so the
document remains useful as a progress dashboard.

Usage:
    python -m mm25DGS_v5_v4.chirp_loop_report
    python -m mm25DGS_v5_v4.chirp_loop_report --out md/chirp_loop_nvs_sweep.md
"""

import os
import json
import argparse
from statistics import mean


PROJECT_ROOT = os.path.abspath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), '..'))
OUTPUT_ROOT = os.path.join(PROJECT_ROOT, 'mm25DGS_v5_v4', 'output_chirp_loop')

# Same 7 priority scenes the sweep orchestrator uses.
SCENES = [
    'seq_0_frame_135',
    'seq_0_frame_390',
    'seq_1_frame_185',
    'seq_1_frame_438',
    'seq_2_frame_105',
    'seq_2_frame_160',
    'seq_2_frame_300',
]


def _result_path(scene, frame, mode, held_out_loop, use_pass2):
    tag = f'frame{frame}_{mode}'
    if mode == 'held_out':
        tag = f'frame{frame}_heldout_loop{held_out_loop}'
    if use_pass2:
        tag = f'{tag}_pass2'
    return os.path.join(OUTPUT_ROOT, f'{scene}_{tag}', 'results.json')


def _load(path):
    if not os.path.isfile(path):
        return None
    try:
        return json.load(open(path))
    except Exception:
        return None


def _discover_frames(scene, data_root, use_pass2):
    """Return the same runnable-frame list the sweep orchestrator used."""
    import glob
    align_dir = os.path.join(data_root, 'alignment_data', scene, 'cascade')
    radar_dir = os.path.join(data_root, scene, 'radar')
    suffix = '_aligned_pass2' if use_pass2 else '_aligned'
    existing = set()
    for p in glob.glob(os.path.join(align_dir, f'cascaded_frame_*{suffix}.json')):
        core = os.path.basename(p).replace(f'{suffix}.json', '')
        core = core.replace('cascaded_frame_', '')
        try:
            existing.add(int(core))
        except ValueError:
            pass
    runnable = []
    for F in sorted(existing):
        if (F - 1) in existing and (F + 1) in existing:
            if os.path.isfile(os.path.join(radar_dir, f'cascaded_frame_{F}.npy')):
                runnable.append(F)
    return runnable


def _fmt(x, width=6, prec=4, miss='   –  '):
    if x is None:
        return miss
    return f'{x:>{width}.{prec}f}'


def _collect(scenes, data_root, held_out_loop, use_pass2):
    """Return a nested dict {scene: {frame: {up, ho, init_up, init_ho, gap}}}.

    ``up`` is Exp A all-16-loop final_train_mean.
    ``ho`` is Exp B held-out loop's final_eval_mean (single-loop mean).
    ``init_up`` / ``init_ho`` come from the per-experiment init_corrs_per_loop.
    ``gap = up − ho``.
    """
    out = {}
    for sc in scenes:
        frames = _discover_frames(sc, data_root, use_pass2)
        out[sc] = {}
        for F in frames:
            up_r = _load(_result_path(sc, F, 'upper_bound', held_out_loop, use_pass2))
            ho_r = _load(_result_path(sc, F, 'held_out', held_out_loop, use_pass2))
            row = {}
            if up_r is not None:
                row['up'] = float(up_r['final_train_mean'])
                ic = up_r.get('init_corrs_per_loop')
                if ic is not None:
                    row['init_up'] = float(mean(ic))
            if ho_r is not None:
                row['ho'] = float(ho_r['final_eval_mean'])
                ic = ho_r.get('init_corrs_per_loop')
                if ic is not None and 0 <= held_out_loop < len(ic):
                    row['init_ho'] = float(ic[held_out_loop])
            if 'up' in row and 'ho' in row:
                row['gap'] = row['up'] - row['ho']
            out[sc][F] = row
    return out


def _scene_mean(frame_rows, key):
    vals = [r[key] for r in frame_rows.values() if key in r]
    return (mean(vals) if vals else None), len(vals)


def _grand_mean(all_rows, key):
    vals = []
    for scene_rows in all_rows.values():
        for r in scene_rows.values():
            if key in r:
                vals.append(r[key])
    return (mean(vals) if vals else None), len(vals)


def build_report(data, held_out_loop, use_pass2):
    lines = []
    lines.append('# Chirp-loop NVS — per-scene × per-frame sweep')
    lines.append('')
    lines.append(f'*Generated by `mm25DGS_v5_v4.chirp_loop_report`.*')
    lines.append('')
    lines.append(f'Alignment anchors: **{"pass-2" if use_pass2 else "pass-1"}** '
                 f'(`_aligned_pass2.json` vs `_aligned.json`).  '
                 f'Held-out loop: **{held_out_loop}** (middle of 16).  '
                 f'Iterations per run: **500**.')
    lines.append('')
    lines.append('### Columns')
    lines.append('')
    lines.append('| column | meaning |')
    lines.append('|---|---|')
    lines.append('| `init_UB` | mean init cc across 16 loops (upper-bound run, untrained ITU concrete) |')
    lines.append('| `UB`      | mean cart_corr across all 16 train loops at best iter (Experiment A — performance ceiling) |')
    lines.append('| `init_HO` | init cc at held-out loop 8 (held-out run, untrained) |')
    lines.append('| `HO`      | cart_corr on the held-out loop 8 at best iter (Experiment B — NVS test result) |')
    lines.append('| `gap`     | `UB − HO` — the interpolation residual on the unseen loop |')
    lines.append('')
    lines.append('A frame marked `–` has not produced a `results.json` yet '
                 '(sweep still running or failed). Frames with only one of '
                 '`UB`/`HO` populated show `gap = –`.')
    lines.append('')

    # Per-scene tables + per-scene means
    for sc, frame_rows in data.items():
        lines.append(f'## `{sc}`')
        lines.append('')
        if not frame_rows:
            lines.append('*(no runnable frames discovered)*')
            lines.append('')
            continue
        lines.append('| frame | init_UB | UB | init_HO | HO | gap |')
        lines.append('|------:|--------:|---:|--------:|---:|----:|')
        for F in sorted(frame_rows):
            r = frame_rows[F]
            lines.append(
                '| {fr} | {iu} | {ub} | {ih} | {ho} | {gp} |'.format(
                    fr=F,
                    iu=_fmt(r.get('init_up')),
                    ub=_fmt(r.get('up')),
                    ih=_fmt(r.get('init_ho')),
                    ho=_fmt(r.get('ho')),
                    gp=_fmt(r.get('gap')),
                ))
        # per-scene means
        m_iu, _ = _scene_mean(frame_rows, 'init_up')
        m_ub, n_ub = _scene_mean(frame_rows, 'up')
        m_ih, _ = _scene_mean(frame_rows, 'init_ho')
        m_ho, n_ho = _scene_mean(frame_rows, 'ho')
        m_gp, n_gp = _scene_mean(frame_rows, 'gap')
        lines.append(
            '| **mean** | **{iu}** | **{ub}** | **{ih}** | **{ho}** | **{gp}** |'.format(
                iu=_fmt(m_iu),
                ub=_fmt(m_ub),
                ih=_fmt(m_ih),
                ho=_fmt(m_ho),
                gp=_fmt(m_gp),
            ))
        lines.append('')
        lines.append(f'*(n_UB={n_ub}, n_HO={n_ho}, n_gap={n_gp} frames)*')
        lines.append('')

    # Grand totals
    lines.append('## Grand means (across all runnable frames, all 7 scenes)')
    lines.append('')
    lines.append('| metric | mean | n |')
    lines.append('|---|---:|---:|')
    for key, label in [
        ('init_up', 'init cc (upper-bound, all 16 loops)'),
        ('up', 'upper-bound cc (all 16 loops)'),
        ('init_ho', 'init cc (held-out loop 8)'),
        ('ho', 'held-out cc (held-out loop 8)'),
        ('gap', 'gap (UB − HO)'),
    ]:
        v, n = _grand_mean(data, key)
        lines.append(f'| {label} | {_fmt(v)} | {n} |')
    lines.append('')

    # Quick header counts
    total_frames = sum(len(x) for x in data.values())
    up_done = sum(1 for x in data.values() for r in x.values() if 'up' in r)
    ho_done = sum(1 for x in data.values() for r in x.values() if 'ho' in r)
    lines.append(f'*Coverage: {up_done}/{total_frames} UB runs, '
                 f'{ho_done}/{total_frames} HO runs.*')
    lines.append('')
    return '\n'.join(lines) + '\n'


def main():
    ap = argparse.ArgumentParser(
        description='Build md/chirp_loop_nvs_sweep.md from sweep results')
    ap.add_argument('--scenes', default=None,
                    help='Comma-separated scene list; default = the 7 priority scenes')
    ap.add_argument('--data-root', default='data')
    ap.add_argument('--held-out-loop', type=int, default=8)
    ap.add_argument('--no-pass2', action='store_true')
    ap.add_argument('--out', default='md/chirp_loop_nvs_sweep.md')
    args = ap.parse_args()

    scenes = args.scenes.split(',') if args.scenes else list(SCENES)
    use_pass2 = not args.no_pass2

    data = _collect(scenes, args.data_root, args.held_out_loop, use_pass2)
    text = build_report(data, args.held_out_loop, use_pass2)

    out_path = os.path.join(PROJECT_ROOT, args.out) \
        if not os.path.isabs(args.out) else args.out
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write(text)
    print(f'wrote {out_path}')
    print(text.splitlines()[-2] if text else '')


if __name__ == '__main__':
    main()
