"""Aggregate frame-NVS results into ``md/frame_nvs.md``.

Collects every ``results.json`` under ``mm25DGS_v5_v4/output_frame_nvs/`` and
produces a pivot report with one row per ``(scene, test_frame, test_loop)``
and one column per experiment variant.

Variants are classified from ``results.json`` contents:

  * ``HO (128)``  — held-out NVS: 8 train frames × 16 loops, test frame
                     excluded from training.
  * ``HO (8)``   — first-chirp held-out NVS: 8 train frames × 1 loop
                     (loop 0 of each), test frame excluded. "First-chirp"
                     here refers to the first chirp loop of each cascaded
                     frame — NOT the separate IWR1443 single-chip radar.
  * ``UB (144)`` — upper bound: 9 train frames × 16 loops, test frame
                     *included* in training (so the test RA is directly
                     supervised).

Any additional variants are surfaced as extra columns automatically.

Every run saves its best-iter model state as ``best_model.pt`` next to
``results.json``; the state dict contains ``positions`` (N,3),
``rotations`` (N,4 quaternion), and ``raw_materials`` (N,6 raw
pre-reparameterization). Physical materials: apply
``mm25DGS_v5_v4.rasterizer.reparameterize_torch``. Surface normals from
rotations: apply ``PointPrimitives.get_normals``.
"""

import os
import json
import glob
import argparse


PROJECT_ROOT = os.path.abspath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), '..'))
OUTPUT_ROOT = os.path.join(PROJECT_ROOT, 'mm25DGS_v5_v4', 'output_frame_nvs')


def _fmt(x, width=6, prec=4, miss='  –  '):
    if x is None:
        return miss
    return f'{x:>{width}.{prec}f}'


def _collect(output_root):
    rows = []
    for p in sorted(glob.glob(os.path.join(output_root, '*', 'results.json'))):
        try:
            r = json.load(open(p))
        except Exception:
            continue
        r['_dir'] = os.path.dirname(p)
        rows.append(r)
    return rows


def _classify_variant(r):
    """Map a results dict to a short variant label.

    Returns (label, key) — label goes on the table header, key is a stable
    dict key used to deduplicate. Also handles older runs that predate the
    ``train_loops`` / ``test_in_train`` fields by inferring from the
    ``train_frames`` list and ``n_train_samples`` count.
    """
    n_frames = len(r.get('train_frames', []))
    # Prefer explicit fields, fall back to inference for legacy runs.
    n_loops = len(r['train_loops']) if 'train_loops' in r else None
    if n_loops is None and 'n_train_samples' in r and n_frames > 0:
        n_loops = int(round(r['n_train_samples'] / n_frames))

    if 'test_in_train' in r:
        test_in_train = bool(r['test_in_train'])
    else:
        test_in_train = int(r['test_frame']) in [int(f) for f in r.get('train_frames', [])]

    samples = r.get('n_train_samples') or (n_frames * (n_loops or 16))

    anchor = r.get('anchor_source', 'pass2_lerp')
    anchor_tag = ' · pass-3' if anchor == 'pass3_per_chirp' else ''
    anchor_key = '_p3' if anchor == 'pass3_per_chirp' else ''

    if test_in_train:
        return (f'UB ({samples}){anchor_tag}', f'UB_{samples}{anchor_key}')
    else:
        if n_loops == 1:
            return (f'HO ({samples}, 1 chirp/frame){anchor_tag}',
                    f'HO_{samples}_1c{anchor_key}')
        return (f'HO ({samples}){anchor_tag}', f'HO_{samples}{anchor_key}')


def _variant_order(key):
    """Stable sort order for variant columns: HO (n), HO (small, 1-chirp), UB (n).
    Pass-3-anchored variants come just after their pass-2 counterparts.
    """
    # Strip _p3 suffix for grouping; track it separately
    is_p3 = key.endswith('_p3')
    base = key[:-3] if is_p3 else key
    if base.startswith('UB_'):
        grp = (2, int(base.split('_')[1]))
    elif base.endswith('_1c'):
        grp = (1, int(base.split('_')[1]))
    else:
        grp = (0, int(base.split('_')[1]))
    return grp + (1 if is_p3 else 0,)


def _pivot(rows):
    """Group rows by (scene, test_frame, test_loop) and variant.

    Returns ``scene_data``: dict keyed by (scene, tf, tl) whose values are:
        {
            'init_train': init_HO for any variant (they're all ~the same
                          since init is ITU concrete regardless),
            'init_ho': similar for init test cc,
            'variants': { variant_key: (label, row_dict) }
        }
    """
    scene_data = {}
    for r in rows:
        key = (r['scene'], r['test_frame'], r['held_out_loop'])
        if key not in scene_data:
            scene_data[key] = {
                'variants': {},
                'init_ho': r.get('init_test_cc'),
                'init_train': r.get('init_train_mean_cc'),
            }
        label, vkey = _classify_variant(r)
        scene_data[key]['variants'][vkey] = (label, r)
    return scene_data


def build_report(rows):
    lines = []
    lines.append('# Frame-level NVS results')
    lines.append('')
    lines.append('*Generated by `mm25DGS_v5_v4.frame_nvs_report`.*')
    lines.append('')
    lines.append('Task: train on `n_train_frames × n_train_loops` chirp-loop '
                 'RA maps from a 9-frame window around a centre frame, hold '
                 'out the middle frame entirely (or include it for the UB '
                 'variant), and evaluate on a single loop of the centre frame.')
    lines.append('')
    lines.append('### Variants')
    lines.append('')
    lines.append('| label | train set | test | description |')
    lines.append('|---|---|---|---|')
    lines.append('| `HO (128)` | 8 frames × 16 loops = 128 RA maps | 1 RA map (centre frame, loop 0) — held out | Standard NVS: held-out frame at frame-scale pose gap. |')
    lines.append('| `HO (8, 1 chirp/frame)` | 8 frames × loop 0 = 8 RA maps | same | First-chirp held-out NVS: only the first chirp loop of each train frame. (The cascaded radar, *not* the IWR1443 single-chip radar — different sensor.) |')
    lines.append('| `UB (144)` | 9 frames × 16 loops = 144 RA maps (**includes the test frame**) | same (but also in train) | Upper bound: the test RA map is directly supervised, giving the ceiling for this scene/pose under the chosen model class. |')
    lines.append('')
    lines.append('`cart_corr` (cart-space normalized cross-correlation) is the '
                 'reported metric. `init_*` columns use the untrained ITU '
                 'concrete model at the exact poses the trained model ends up '
                 'rendering at.')
    lines.append('')

    if not rows:
        lines.append('*(no results.json files under `mm25DGS_v5_v4/output_frame_nvs/`)*')
        lines.append('')
        return '\n'.join(lines) + '\n'

    scene_data = _pivot(rows)

    # Discover variants across ALL scenes for consistent columns
    all_vkeys = set()
    for d in scene_data.values():
        all_vkeys.update(d['variants'].keys())
    ordered_vkeys = sorted(all_vkeys, key=_variant_order)

    # Pretty labels: use the label from the most recent row that defined the variant
    vlabels = {}
    for d in scene_data.values():
        for vkey, (lbl, _row) in d['variants'].items():
            vlabels[vkey] = lbl

    lines.append('## Results — pivot (one row per scene)')
    lines.append('')
    header_cols = ['scene', 'test (frame / loop)', 'init_HO']
    for vk in ordered_vkeys:
        header_cols.append(vlabels[vk])
    header_cols.append('init_train')
    for vk in ordered_vkeys:
        header_cols.append(f'final_train · {vlabels[vk]}')

    # markdown header
    lines.append('| ' + ' | '.join(header_cols) + ' |')
    aligns = ['---'] + ['---'] + ['---:'] * (len(header_cols) - 2)
    lines.append('| ' + ' | '.join(aligns) + ' |')

    for (scene, tf, tl), d in sorted(scene_data.items()):
        row_cells = [f'`{scene}`', f'{tf} / {tl}', _fmt(d['init_ho'])]
        for vk in ordered_vkeys:
            v = d['variants'].get(vk)
            if v is None:
                row_cells.append('  –  ')
            else:
                row_cells.append(f'**{_fmt(v[1].get("final_test_cc"))}**')
        row_cells.append(_fmt(d['init_train']))
        for vk in ordered_vkeys:
            v = d['variants'].get(vk)
            if v is None:
                row_cells.append('  –  ')
            else:
                row_cells.append(_fmt(v[1].get('final_train_mean_cc')))
        lines.append('| ' + ' | '.join(row_cells) + ' |')

    lines.append('')

    # Per-scene details block
    lines.append('## Per-scene details')
    lines.append('')
    for (scene, tf, tl), d in sorted(scene_data.items()):
        lines.append(f'### `{scene}`  —  test frame `{tf}` loop `{tl}`')
        lines.append('')
        lines.append('| variant | n_frames × n_loops | align | iters | best iter | init_HO → HO (Δ) | init_train → final_train (Δ) | elapsed |')
        lines.append('|---|---|---|---:|---:|---|---|---:|')
        for vk in ordered_vkeys:
            v = d['variants'].get(vk)
            if v is None:
                continue
            lbl, r = v
            n_frames = len(r.get('train_frames', []))
            n_loops = len(r['train_loops']) if 'train_loops' in r else int(round(r.get('n_train_samples', 0) / max(n_frames, 1)))
            iters = r.get('num_iters')
            best_it = r.get('best_iter')
            init_ho = r.get('init_test_cc')
            fin_ho = r.get('final_test_cc')
            init_tr = r.get('init_train_mean_cc')
            fin_tr = r.get('final_train_mean_cc')
            elapsed = r.get('elapsed_s')
            lines.append(
                f'| `{lbl}` '
                f'| {n_frames} × {n_loops} = {r.get("n_train_samples", n_frames * n_loops)} '
                f'| {r.get("alignment_source", "?")} '
                f'| {iters} '
                f'| {best_it} '
                f'| {init_ho:.4f} → **{fin_ho:.4f}** '
                f'({fin_ho - init_ho:+.4f}) '
                f'| {init_tr:.4f} → {fin_tr:.4f} '
                f'({fin_tr - init_tr:+.4f}) '
                f'| {int(elapsed) if elapsed is not None else "–"} s |'
            )
        lines.append('')

    # Confirmation block on saved state
    lines.append('## Saved state (for downstream analysis)')
    lines.append('')
    lines.append('Every run saves its best-iter model state to '
                 '`mm25DGS_v5_v4/output_frame_nvs/<scene>_<tag>/best_model.pt`. '
                 'The state dict contains:')
    lines.append('')
    lines.append('| key | shape | meaning |')
    lines.append('|---|---|---|')
    lines.append('| `positions`     | `(N, 3)` | per-point xyz positions (frozen; from LiDAR pcl.npy → FPS) |')
    lines.append('| `rotations`     | `(N, 4)` | per-point quaternion `[w, x, y, z]` — trainable |')
    lines.append('| `raw_materials` | `(N, 6)` | per-point material params in raw/pre-reparameterisation space — trainable |')
    lines.append('')
    lines.append('To recover physical material values: '
                 '`physics = mm25DGS_v5_v4.rasterizer.reparameterize_torch(raw_materials)` '
                 '→ `(N, 6)` `[eps_real, eps_imag, sigma_h, l_c, tau, thickness]`. '
                 'Surface normals: `PointPrimitives.get_normals()` — third column of '
                 'the quaternion-to-rotation-matrix.')
    lines.append('')
    lines.append('`history.npz` additionally records per-iteration `mean_train_cc` and `loss`.')
    lines.append('')

    return '\n'.join(lines) + '\n'


def main():
    ap = argparse.ArgumentParser(
        description='Build md/frame_nvs.md from frame-NVS results')
    ap.add_argument('--output-root', default=OUTPUT_ROOT)
    ap.add_argument('--out', default='md/frame_nvs.md')
    args = ap.parse_args()

    rows = _collect(args.output_root)
    text = build_report(rows)

    out_path = (args.out if os.path.isabs(args.out)
                else os.path.join(PROJECT_ROOT, args.out))
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write(text)
    print(f'wrote {out_path}  ({len(rows)} result(s))')


if __name__ == '__main__':
    main()
